name: On PR
on: 
  pull_request:
    branches: [master]

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile

      - run: yarn lint

      - run: yarn format:check
